version: '3.5'
services:
  app:
    image: linuxserver/duplicati
    environment:
            - PUID=$PUID
            - PGID=$PGID
    volumes:
            - config:/config
            - backups:/backups
            - source:/source
            - ~/bwdata:/bwdata:ro
            - ~/duplicati:/duplicati:ro
    restart: unless-stopped
  haproxy:
    image: haproxy:latest
    environment:
            - PUID=$PUID
            - PGID=$PGID
            - APP_HOST=app
            - APP_PORT=$APP_PORT
            - HAPROXY_PORT=$HAPROXY_PORT
            - HAPROXY_SSL_KEY_PATH=/usr/local/etc/haproxy/$SSL_CERT_NAME
    volumes:
            - ./haproxy:/usr/local/etc/haproxy:ro
            - /var/run/docker.sock:/var/run/docker.sock
    ports:
            - $OUT_PORT:$HAPROXY_PORT
    depends_on:
            - app
    restart: unless-stopped
volumes:
    config:
    backups:
    source:

